#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"

#pragma config(Motor,  port2,           FrontRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BackRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BackLeft,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  motor[port6] = 127;
  motor[port7] = -127;
  motor[port8] = 127;
  motor[port9] = -127;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while (true)
	{
		motor[port2] = vexRT[Ch2];
		motor[port3] = vexRT[Ch2];
		motor[port4] = -vexRT[Ch3];
		motor[port5] = -vexRT[Ch3];
	}
}
