#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  leftSpineSW,    sensorTouch)
#pragma config(Sensor, dgtl2,  rightSpineSW,   sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rareLaunch,    tmotorVex393_HBridge, openLoop, reversed) //RARE
#pragma config(Motor,  port2,           rightForward,  tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_1) //JUAN
#pragma config(Motor,  port3,           leftForward,   tmotorVex393_MC29, openLoop, reversed, driveLeft, encoderPort, I2C_2)//DEAG
#pragma config(Motor,  port4,           rightRear,     tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_3) //DANK
#pragma config(Motor,  port5,           leftRear,      tmotorVex393_MC29, openLoop, reversed, driveLeft, encoderPort, I2C_4) //MEMES
#pragma config(Motor,  port6,           leftSpine,     tmotorVex393_MC29, openLoop, reversed) //JOHN
#pragma config(Motor,  port7,           rightSpine,    tmotorVex393_MC29, openLoop) //CENA
#pragma config(Motor,  port8,           intake,        tmotorVex393_MC29, openLoop) //WOMBO
#pragma config(Motor,  port9,           cam,           tmotorServoStandard, openLoop)//COMBO
#pragma config(Motor,  port10,          pepesLaunch,    tmotorVex393_HBridge, openLoop) //PEPES
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
