#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    fbAccel,        sensorAccelerometer)
#pragma config(Sensor, in2,    lrAccel,        sensorAccelerometer)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  leftSpineSW,    sensorTouch)
#pragma config(Sensor, dgtl2,  rightSpineSW,   sensorTouch)
#pragma config(Sensor, dgtl3,  ballSW,         sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rareLaunch,    tmotorVex393_HBridge, PIDControl, encoderPort, I2C_5)
#pragma config(Motor,  port2,           rightForward,  tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           leftForward,   tmotorVex393_MC29, openLoop, reversed, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port4,           rightRear,     tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_3)
#pragma config(Motor,  port5,           leftRear,      tmotorVex393_MC29, openLoop, reversed, driveLeft, encoderPort, I2C_4)
#pragma config(Motor,  port6,           leftSpine,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightSpine,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           cam,           tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          pepesLaunch,   tmotorVex393_HBridge, PIDControl, reversed, encoderPort, I2C_6)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	motor[intake] = 127;
  while(true){
		while(SensorValue[ballSW]==0){}
		motor[leftSpine] = 63;
		motor[rightSpine] = 63;
		while(SensorValue[leftSpineSW]==0||SensorValue[rightSpineSW]==0){}
		while(SensorValue[leftSpineSW]==1||SensorValue[rightSpineSW]==1){}
		motor[leftSpine] = 0;
		motor[rightSpine] = 0;
	}
}
